#!/usr/bin/env bash
set -euo pipefail

SCRIPT_SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SCRIPT_SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" >/dev/null 2>&1 && pwd)"
  SCRIPT_SOURCE="$(readlink "$SCRIPT_SOURCE")"
  [[ $SCRIPT_SOURCE != /* ]] && SCRIPT_SOURCE="$DIR/$SCRIPT_SOURCE"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_SOURCE")" >/dev/null 2>&1 && pwd)"

if [ -n "${SUDO_USER:-}" ]; then
  USER_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
else
  USER_HOME="$HOME"
fi

DOTFILES_ENV="$USER_HOME/.dotfiles-env"

if [ -f "$DOTFILES_ENV" ]; then
  source "$DOTFILES_ENV"
fi

if [ -z "${DOTFILES:-}" ] || [ "$DOTFILES" != "$SCRIPT_DIR/dotfiles" ]; then
  echo "Setting up DOTFILES environment..."

  mkdir -p "$(dirname "$DOTFILES_ENV")"

  cat > "$DOTFILES_ENV" << EOF
# Auto-generated by ubuntu-utility envsetup.sh
# Do not edit manually
export DOTFILES="$SCRIPT_DIR/dotfiles"
EOF

  SHELL_RC="$USER_HOME/.bashrc"
  DOTFILES_SOURCE_LINE='[ -f "$HOME/.dotfiles-env" ] && source "$HOME/.dotfiles-env"'

  if [ -f "$SHELL_RC" ] && ! grep -qF '.dotfiles-env' "$SHELL_RC" 2>/dev/null; then
    echo "" >> "$SHELL_RC"
    echo "# Dotfiles environment" >> "$SHELL_RC"
    echo "$DOTFILES_SOURCE_LINE" >> "$SHELL_RC"
    echo "Added DOTFILES to .bashrc"
  fi

  source "$DOTFILES_ENV"
  echo "DOTFILES=$DOTFILES"
fi
